services:
  asa_server:
    tty: true
    restart: unless-stopped
    #image: azixus/ark-ascended-docker
    build:
      context: .
      args:
        PUID: ${PUID}
        PGID: ${PGID}
        TINI_VERSION: ${TINI_VERSION}
    env_file:
      - .env
    environment:
      SERVER_MAP: TheIsland_WP
      SERVER_PORT: 7790
      SESSION_NAME: My Awesome Server
      AUTO_UPDATE_CRON_EXPRESSION: "0 * * * *"
    volumes:
      - ./ark_data:/opt/arkserver
      - ./ark_backup:/var/backups/asa-server
      - steam_data_asa_server:/opt/steamcmd
      - shared_cluster:/opt/shared-cluster #Enable for Cluster config
    ports:
      - "7790:7790/udp"
      #- "${SERVER_PORT}:${SERVER_PORT}/udp"
      #- "${RCON_PORT}:${RCON_PORT}/tcp"
    stop_grace_period: 45s
  config:
    image: python:3.9
    entrypoint: python3 -m http.server --directory /web 80
    volumes:
      - ./web:/web
      - steam_data_asa_server:/opt/steam
volumes:
    steam_data_asa_server:
    shared_cluster:
