services:
  server:
    tty: true
    restart: unless-stopped
    build:
      context: .
      args:
        - PGID
        - PUID
    env_file:
      - .env
    environment:
      SERVER_MAP: TheIsland_WP # Change Map
      SESSION_NAME: My Awesome Server # Change Server Name
      AUTO_UPDATE_CRON_EXPRESSION: "0 * * * *" 
    volumes:
      - ./ark_data:/opt/arkserver
      - ./ark_backup:/var/backups/asa-server
      - steam_data_server:/opt/steamcmd
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
      #- "${RCON_PORT}:${RCON_PORT}/tcp"
    stop_grace_period: 45s
  # config: # Uncomment Service if you want to use Dynamicconfig
  #   image: python:3.9
  #   entrypoint: python3 -m http.server --directory /web 80
  #   volumes:
  #     - ./web:/web
volumes:
    steam_data_server:
